#!/usr/bin/env bash
set -euo pipefail

################################################################################
# Copy GSEAPreranked OmicsKit-ready outputs into an OmicsKit repository.
#
# Usage:
#   bash preranked/scripts/03_copy_omicskit_ready_outputs.sh ../OmicsKit
################################################################################

if [[ $# -lt 1 ]]; then
  echo "Usage: bash preranked/scripts/03_copy_omicskit_ready_outputs.sh /path/to/OmicsKit" >&2
  exit 1
fi

OMICKIT_DIR="$1"

if [[ ! -d "${OMICKIT_DIR}" ]]; then
  echo "ERROR: OmicsKit directory not found: ${OMICKIT_DIR}" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRERANKED_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
EXAMPLE_DIR="${PRERANKED_DIR}/examples/brca"

READY_DIR="${EXAMPLE_DIR}/omicskit_ready"
RNK_DIR="${EXAMPLE_DIR}/rnk"

DEST_DIR="${OMICKIT_DIR}/inst/extdata/brca/gsea_outputs"
DEST_RNK_DIR="${DEST_DIR}/rnk"

mkdir -p "${DEST_DIR}"
mkdir -p "${DEST_RNK_DIR}"

if compgen -G "${READY_DIR}/*.tsv" > /dev/null; then
  cp "${READY_DIR}"/*.tsv "${DEST_DIR}/"
else
  echo "ERROR: No OmicsKit-ready TSV files found in ${READY_DIR}" >&2
  exit 1
fi

if compgen -G "${RNK_DIR}/*.rnk" > /dev/null; then
  cp "${RNK_DIR}"/*.rnk "${DEST_RNK_DIR}/"
fi

if compgen -G "${RNK_DIR}/*_metadata.tsv" > /dev/null; then
  cp "${RNK_DIR}"/*_metadata.tsv "${DEST_RNK_DIR}/"
fi

cat > "${DEST_DIR}/README.md" <<'EOF'
# TCGA-BRCA GSEAPreranked outputs

These files contain standardized GSEAPreranked outputs generated by the
GSEA-Pipeline `preranked/` workflow.

## Comparisons

- ERpositive_vs_ERnegative
- Tumor_vs_Normal

## Gene-set collections

- Hallmark
- GO Biological Process

## Files

- GSEA_ERpositive_vs_ERnegative_Hallmark.tsv
- GSEA_ERpositive_vs_ERnegative_GO_BP.tsv
- GSEA_Tumor_vs_Normal_Hallmark.tsv
- GSEA_Tumor_vs_Normal_GO_BP.tsv
- GSEA_BRCA_all_comparisons_Hallmark_GO_BP.tsv

## RNK files

The ranked lists used to run GSEAPreranked are stored under:

```text
rnk/
```

## Notes

The MSigDB GMT files are not included. They should be downloaded directly from
MSigDB according to the user's registration and usage terms.
EOF

echo "Copied OmicsKit-ready GSEAPreranked outputs to:"
echo "  ${DEST_DIR}"
